### ISSUE TITLE
[PE-D][Tester F] Editing a task's module code with insensitive case

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F11-2/tp#219]
![Screenshot 2022-10-28 at 4.45.18 PM.png](https://raw.githubusercontent.com/zsiggg/ped/main/files/26daeb25-2f75-4fb2-88a8-4ef8b7285f86.png)

Editing a task and specifying a differently cased module code works, which is good since module code is interpreted in a case-insensitive manner, but the UI shows the wrongly cased module code in the task. 

Thus, the module code shown in task and the actual module's module code is differently cased in the UI. 

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: zsiggg/ped#4

**Comment by RachelChua** [comment]
We will implement this in the future.
