### ISSUE TITLE
[PE-D][Tester D] Exam Parameter: missing exam time and venue.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F11-2/tp#231]
![image.png](https://raw.githubusercontent.com/rexong/ped/main/files/e1c65f32-3031-4747-9013-5fa7dee76d01.png)

I think as a user, I would like to key in the time and venue of the exam so I can look it up in modpro when I need to. However, it is not implemented in your application.

I would suggest if possible to add in your user guide "coming soon" feature.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: rexong/ped#9

**Comment by phualiting** [comment]
We will implement this in the future.
